In [36]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('./多元统计.csv', header=None)

In [8]:
df.head()

0     1     2     3      4
0   87.9  19.6   1.0  1661  28.37
1   89.9  15.2  90.1   968  28.77
2  153.0  19.7  56.6  1353  26.04
3  132.0  17.0  91.0  1293  25.74
4   88.8  18.3  93.7  1153  26.68

**数据说明**
对其进行PCA主成分分析并降维
* x1: 11、 12月 降水量
* x2: 7月份的平均温度
* x3: 7月份的降水量
* x4: 7月份的辐射
* x5: 农作物的平均产量

In [11]:
def Center_stadardization(X):
    X -= np.mean(X, axis =0)
    X /= np.std(X, axis = 0)
    return X
8im 

In [21]:
mat = np.mat(Center_stadardization(np.array(df)))
eigenvalue, featurevector = np.linalg.eig(mat.T * mat)
print("特征值：",eigenvalue)
print("特征向量：", featurevector)

特征值： [33.93133277 14.9921314   3.2721122   1.22707347  1.57735015]
特征向量： [[-0.37480383  0.5817003  -0.49818036 -0.48446445  0.19559493]
 [ 0.3792745   0.54733987  0.67846509 -0.29450114  0.0975916 ]
 [-0.53201906 -0.09255771  0.33218039 -0.32452519 -0.70194614]
 [ 0.47903328  0.36242998 -0.38262666  0.18459298 -0.67726944]
 [ 0.45072805 -0.47129759 -0.18642552 -0.7342834  -0.02821746]]


In [27]:
n, p = featurevector.shape
for i in range(p):
    print('C_{}, q={}'.format(i, i), 
          np.sum(eigenvalue[:i+1]) / np.sum(eigenvalue))
C_0 = 0.85

C_0, q=0 0.6169333231466
C_1, q=1 0.8895175304906894
C_2, q=2 0.9490104795333598
C_3, q=3 0.971320906273599
C_4, q=4 1.0


即 q = 2时， alpha_q >= c_0
那么前2个主成分为

In [51]:
q = 4
Y = mat * featurevector[:,:q]
Y

matrix([[ 3.53119714,  0.52091093, -0.01134875,  0.37454166],
        [-0.63726541, -2.89629282, -0.46277355, -0.13508567],
        [ 0.9695343 ,  1.32520328,  0.54995853, -0.35676394],
        [-0.40241902, -0.29772803, -0.24700903,  0.27035575],
        [ 0.23840231, -0.7565326 ,  1.17083267, -0.01997539],
        [-1.50768899,  1.5530064 , -0.55616819, -0.58745356],
        [ 0.43142733, -0.88574217,  0.253751  , -0.46972202],
        [ 2.1299292 , -0.02431735, -0.44349486, -0.00455346],
        [-0.17807109,  0.53831452, -0.21156772,  0.32535503],
        [-3.38388359,  0.42802413,  0.57366042,  0.38581916],
        [-1.19116218,  0.49515372, -0.61584054,  0.21748245]])

In [50]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
newX = pca.fit_transform(mat)
newX

array([[ 3.53119714, -0.52091093, -0.01134875, -0.06659273],
       [-0.63726541,  2.89629282, -0.46277355, -0.07101226],
       [ 0.9695343 , -1.32520328,  0.54995853, -0.24216575],
       [-0.40241902,  0.29772803, -0.24700903,  0.57160624],
       [ 0.23840231,  0.7565326 ,  1.17083267,  0.30153638],
       [-1.50768899, -1.5530064 , -0.55616819,  0.37498827],
       [ 0.43142733,  0.88574217,  0.253751  , -0.49124522],
       [ 2.1299292 ,  0.02431735, -0.44349486,  0.48978896],
       [-0.17807109, -0.53831452, -0.21156772, -0.50741275],
       [-3.38388359, -0.42802413,  0.57366042,  0.09196636],
       [-1.19116218, -0.49515372, -0.61584054, -0.4514575 ]])